# Generated by Django 4.2.6 on 2023-10-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_mobileinformation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileinformation',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mobileinformation',
            name='price',
            field=models.IntegerField(),
        ),
    ]
