# Generated by Django 4.2.6 on 2023-10-12 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_mobileinformation_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileinformation',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.mobileinformation')),
            ],
        ),
    ]
