# Generated by Django 4.2.6 on 2023-10-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_mobileinformation_stock_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileinformation',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
