# Generated by Django 4.2.6 on 2023-10-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_mobileinformation_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileinformation',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
