# Generated by Django 4.2.6 on 2023-10-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_mobileinformation_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobileinformation',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
